config/routes.rb
Rails.application.routes.draw do
  get "forms/new"
  post "forms/create" #投稿を保存するためにhttpメソッドはPOST
  root "forms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/models/form.rb
class Form < ApplicationRecord
  validates :name,:email,:content, presence: true
end

app/models/top.rb
class Top < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
  end
  
  def new
    @form = Form.new
  end

  def create
    @form = Form.create(form_params)  #格納された値を保存
  end

  private
  def form_params
      params.require(:form).permit(:name, :email, :phone, :content)  #paramsの中身をpermitして保存を許可
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @form = Form.new
  end

  def create
    Form.create(form_params)
    redirect_to action: 'index'
  end

private
  def form_params
      params.require(:form).permit(:name, :email, :content) 
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/contacts/new.html.haml
= form_for @contact do |f|
  .form-group
    = f.label :email, '返信先メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :message, 'お問い合わせ内容'
    = f.text_area :message, size: '10x10', class: 'form-control'
  = f.submit '送信'

app/views/forms/index.html.haml
.html
  = render 'shared/top_bar'
  .about{ id: "1"}
    .about__text
      %h1 このサイトは我が家の家族
      %br 「がぶちゃん・めいちゃん」を
      %br 紹介するサイトです。
      %i.fas.fa-cat.fa-spin
  .history{ id: "2"}
    %h1
      history
    .history__box
      .history__box__start
      .history__box__text
        %p 2018/4 子ねこの里親会でもらってきた。
        %br
        %p 双子の猫ちゃん黒→めいちゃん三毛猫→がぶちゃん
    .history__box
      .history__box__circle
      .history__box__text
        %p 2018/10 約半年で3kgから5kgに成長
      -# .history__box__img
      -#   %img{alt: "", src: "/assets/IMG_5428.JPG"}
      -#   %img{alt: "", src: "/assets/IMG_5429.JPG"}
    .history__box
      .history__box__circle
      .history__box__text
    .history__box
      .history__box__circle
      .history__box__text
  .image{ id: "3"}
    %h1
      image
    .multiple
      %div
        %img{:alt => "", :src => "/assets/IMG_4739.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_4882.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_4967.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5143.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5178.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5283.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5311.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5324.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5325.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5327.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5330.JPG"}/
      %div
        %img{:alt => "", :src => "/assets/IMG_5331.JPG"}/
  .contact{ id:"4"}
    .contact__box
      = form_for(@form, url: forms_create_path) do |f|
        .form-group
          = f.text_field :name, class: 'form-control1', placeholder: 'あなたのお名前 *', id: 'name'
        .form-group
          = f.text_field :email, class: 'form-control2', placeholder: 'メールアドレス *', id: 'email'
        .form-group
          = f.text_area :content, class: 'form-control3', placeholder: 'お問い合わせ内容 *', id: 'content'
        .clearfix
          = f.submit "メッセージを送信する", class:'btn btn-primary btn-xl text-uppercase'
    .contact_text
      = fa_icon 'envelope', class: 'icon'
  
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CatMeet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', data:{ turbolinks:{ track: true }}
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
  %body
    = yield

app/views/shared/_top_bar.html.haml
.top-bar
  .top-bar__title
    cat-meet
  %ul.top-bar__nav
    %li.top-bar__nav__list
      %a{href:"#1"}about
    %li.top-bar__nav__list
      %a{href:"#2"}history
    %li.top-bar__nav__list
      %a{href:"#3"}image
    %li.top-bar__nav__list
      %a{href:"#4"}contact